spring:
  thymeleaf:
    cache: false
  datasource:
    generate-unique-name: false
    url: jdbc:h2:~/tacocloud
    driverClassName: org.h2.Driver
    username: taco
    password: taco
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

